@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 1,
    "backwardDepth": 1,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": false, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "GPXrechner.Application.Instructions.GetDistance",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1072845520 { 
   	label=Application
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   UserOutput402627690[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)UserOutput</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ alertGranularityTooHigh(granularity: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ alertWrongFileType(filePath: String, expected: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ info(s: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ infoEstimatedTime(pathName: String, estimatedTime: Duration)</TD></TR>
<TR><TD ALIGN="LEFT" >+ infoGeneratedTrack(trackName: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ infoPMS(pms: MovementSpeed)</TD></TR>
<TR><TD ALIGN="LEFT" >+ infoPMSofTour(tourName: String, pms: MovementSpeed)</TD></TR>
<TR><TD ALIGN="LEFT" >+ infoPathElevationGain(pathname: String, elevationGain: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ infoPathLength(pathName: String, length: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ infoTimeTaken(tourName: String, timeTaken: Duration)</TD></TR>
<TR><TD ALIGN="LEFT" >+ infoWayPointsToSplit(splitPoints: WayPointSet)</TD></TR>
<TR><TD ALIGN="LEFT" >+ printBoolMatrix(matrix: boolean[][])</TD></TR>
<TR><TD ALIGN="LEFT" >+ provideEvaluationFunctions(evaluationFunctions: EvaluationFunction[])</TD></TR>
<TR><TD ALIGN="LEFT" >+ provideInstructions(instructions: Instruction[])</TD></TR>
<TR><TD ALIGN="LEFT" >+ provideSports()</TD></TR>
<TR><TD ALIGN="LEFT" >+ showElevationProfile(tourName: String, elevationProfile: ElevationProfile)</TD></TR>
<TR><TD ALIGN="LEFT" >+ showSpeedProfile(tourName: String, speedProfile: SpeedProfile)</TD></TR>
<TR><TD ALIGN="LEFT" >+ userToGiveClassPath(basePath: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ userToGiveClassPath(basePath: String, abortOption: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ userToProvideGranularity()</TD></TR>
<TR><TD ALIGN="LEFT" >+ userToProvideInstruction()</TD></TR>
<TR><TD ALIGN="LEFT" >+ userToProvideMovementSpeed()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];

subgraph cluster_1114602656 { 
   	label=States
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   State534505338[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)State</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getPath(): Path</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];
} 

subgraph cluster_899390013 { 
   	label=Instructions
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   GetDistance1197983005[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)GetDistance</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   userOutput: UserOutput [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ execute(state: State): State</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Instruction1197983005[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)Instruction</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ execute(state: State): State</TD></TR>
<TR><TD ALIGN="LEFT" >+ getDescription(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ getRegex(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];
} 
} 

subgraph cluster_2052636900 { 
   	label=Domain
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1146139724 { 
   	label=Calculations
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   DistanceCalculator1949287398[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)DistanceCalculator</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ calc2dDistance(a: Location, b: Location): Distance</TD></TR>
<TR><TD ALIGN="LEFT" >+ calc2dDistance(path: Path): Distance</TD></TR>
<TR><TD ALIGN="LEFT" >+ calc3dDistance(a: Location, b: Location): Distance</TD></TR>
<TR><TD ALIGN="LEFT" >+ calc3dDistance(path: Path): Distance</TD></TR>
<TR><TD ALIGN="LEFT" >+ calcAvgAlt(list: List&lt;Location&gt;): Elevation</TD></TR>
<TR><TD ALIGN="LEFT" >- calcDeltaLat(a: Location, b: Location): Distance</TD></TR>
<TR><TD ALIGN="LEFT" >- calcDeltaLon(a: Location, b: Location): Distance</TD></TR>
<TR><TD ALIGN="LEFT" >+ calcElevationGain(a: Location, b: Location): ElevationGain</TD></TR>
<TR><TD ALIGN="LEFT" >+ calcElevationGain(path: Path): ElevationGain</TD></TR>
<TR><TD ALIGN="LEFT" >+ calcMaxAlt(list: List&lt;Location&gt;): Elevation</TD></TR>
<TR><TD ALIGN="LEFT" >+ calcMinAlt(list: List&lt;Location&gt;): Elevation</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
GetDistance1197983005 -> DistanceCalculator1949287398[label="execute() -> calc3dDistance()"];
GetDistance1197983005 -> State534505338[label="execute() -> getPath()"];
GetDistance1197983005 -> UserOutput402627690[label="userOutput
[0..1]"];
Instruction1197983005 -> GetDistance1197983005[arrowhead=none, arrowtail=empty, dir=both];
    
}
@enduml